services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command:
      - start
      - --log=warn
      - --user=root
      - --pass=root
    restart: always
    profiles:
      - local
